### ISSUE TITLE
Workflow for preregistrations

### ISSUE THREAD

**Issue by Futrell** [Futrell/rnnpsycholing#2]
I'm pushing in some preregistration previews from aspredicted.org, based on the README files for the experiments.

In an ideal world, it would work like this: one of us decides to start running an experiment. We press the button to submit the preregistration that's sitting there ready to go, and then do the analysis. 

I don't see how to make that happen, so I propose we push in these preregistration previews, then when one of us decides to start running an experiment, we go and submit the preregistration on aspredicted.org by copying the information into the website.

What do you all think?

**Comment by wilcoxeg** [comment]
That sounds good. I pushed one of the pre registrations (for the other garden path sentences) to the repo. 

One problem is this: there's one pre-registration for both LSTMs, so we might just want to submit all the pre-registrations before we start doing any of the experiments? (Is that kosher?)

Ethan

**Comment by Futrell** [comment]
I think it would be legal to submit all the preregistrations at once before running any experiments, but I don't want us to get blocked waiting for any one to get done, so I'd prefer to do them separately.

**Comment by Futrell** [comment]
Better idea: For all the preregistrations I've pushed in, I've sent a copy to myself for approval. Unfortunately I can't share the approval link with other people. If you want to begin an experiment, and you don't want to change the preregistration, just tell me and I'll press the button on my end to make it official.

**Comment by wilcoxeg** [comment]
Okay. I think I'm going to try to get all the google lstm ones tomorrow for English.

I'm working on a script right now that will generate all the test sentences from the excell spreadsheets, and I hope to push that tomorrow morning. I'll let you know tomorrow when I start running the experiments.
