### ISSUE TITLE
gardenpathing verb ambiguity with intervening phrase, last item has problem

### ISSUE THREAD

**Issue by rlevy** [Futrell/rnnpsycholing#4]
"grazed" doesn't work well as a transitive verb, I think (meaning is really different).  Ethan can you fix this?

**Comment by wilcoxeg** [comment]
Got it! I changed it to "The doctor (who was) hurried/born down the hallway remembered to bring his stethoscope."

**Comment by rlevy** [comment]
Do you mean “borne” instead of “born”?
